- handlers/missing_test/__init__.py
- handlers/missing_test/tests/new_pr.json
Fixes #35.
I've done my best to maximize readability. If you have any complaint, I'd be happy to fix it.
> Check for the presence of tests in more PRs

- README.md
Based on how the github.com/servo/servo hook is configured.
> Document repo-side hook settings

- handlers/nonini_wpt_meta/__init__.py
- handlers/nonini_wpt_meta/tests/new_pr.json
> Shh ignore manifestjson updates

- README.md
- config.sample
r? @jdm 
Could you check whether I guessed correctly on the config format and required permissions on the API token?
> Example config

- handlers/watchers/__init__.py
- handlers/watchers/tests/new_pr.json
- handlers/watchers/watchers.ini
I have used this https://docs.python.org/2/tutorial/controlflow.html#break-and-continue-statements-and-else-clauses-on-loops. I don't understand how the test work, how should I add one ?
> Support file path exclusions in watcher handler. Issue #76

- .travis.yml
Homu isn't actually listening yet, but hey :)
re https://github.com/servo/saltfs/pull/297
r? @jdm
> Add Homu webhook

- collaborators.ini
@larsbergstrom set up the highfive webhook for saltfs.
> Add aneeshusa as a collaborator for servo/saltfs

- handlers/watchers/watchers.ini
I'd like to watch the constellation and webdriver crates.
> Added watcher for asajeffrey.

- collaborators.ini
- handlers/assign_reviewer/tests/new_pr_author_is_only_collaborator.json
- handlers/assign_reviewer/tests/new_pr_without_reviewer.json
I'm willing to share @jdm's PR load :joy:
> Add waffles to collaborators for highfive

- handlers/easy_info/__init__.py
- handlers/easy_info/tests/label_easy.json
- handlers/easy_info/tests/label_not_easy.json
- json_cleanup.py
> Mention that issues labeled E-Easy should be claimed

- handlers/label_watchers/__init__.py
- handlers/label_watchers/tests/dont_label_sender.json
- handlers/label_watchers/tests/dont_notify_creator.json
- handlers/label_watchers/tests/new_pr.json
It's annoying when highfive notifies the issue/PR author (when he's a label watcher)
> Highfive shouldn't notify if author is a watcher

- handlers/watchers/watchers.ini
Want to watch the new stuff coming in https://github.com/servo/servo/pull/13204
r? @jdm
> Watch more directories

- README.md
Now, the comments look like comments :smile:
> Fix the comments in JSON in README

- handlers/watchers/watchers.ini
> Watch even more directories

- collaborators.ini
I'll still accept r?, but I can no longer serve my duties in the rotation.
r? @jdm
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/highfive/161)
> Remove larsbergstrom from the rotation

- collaborators.ini
I recently changed my github username to cbrewster to match up with IRC.
> Change ConnorGBrewster to cbrewster

- collaborators.ini
Taking time off for a week, then I’ll be traveling for three weeks in April.
> Remove myself from auto-assigned reviewers for now

- handlers/watchers/__init__.py
Only the first five files are shown.
"and n more" tells how many files were omitted.
closes #175
> Cap number of files that are listed in "heads up" comment

- handlers/label_watchers/watchers.ini
- handlers/watchers/watchers.ini
This rebases the functional parts of #182. We can sort the lists another time.
> Add edunham to watchers

- handlers/watchers/watchers.ini
I would like to add myself to style watchers list.
> Add canaltinova to watchers list

- collaborators.ini
I still plan to do this as time allows,
but realistically I no longer have time to respond to all incoming PRs,
so reflect reality in the config file.
> Stop automatically reviewing saltfs changes

- handlers/label_watchers/watchers.ini
Adding @thenadj as a watcher for all new `Design`-tagged issues in mozillareality/firefoxreality
r? @jdm
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/highfive/203)
> Add a user to the Firefox Reality repository

- handlers/label_watchers/watchers.ini
- handlers/watchers/watchers.ini
As much as I've enjoyed working with all the great Servo folks,
I unfortunately don't have time to keep up with the project these days.
> Stop watching servo bits

- .travis.yml
- handlers/homu_status/__init__.py
https://github.com/servo/saltfs/pull/906#issuecomment-436313032
> Remove unneeded webhook notification

- handlers/watchers/watchers.ini
> Remove Paul from watchers.ini

- handlers/assign_reviewer/__init__.py
- handlers/assign_reviewer/tests/new_pr_author_is_only_collaborator.json
- handlers/assign_reviewer/tests/new_pr_author_is_reviewer.json
- handlers/assign_reviewer/tests/new_pr_with_reviewer.json
- handlers/assign_reviewer/tests/new_pr_with_reviewer_requested.json
- handlers/assign_reviewer/tests/new_pr_without_reviewer.json
> Don't override review requests.

- eventhandler.py
- handlers/status_update/__init__.py
- handlers/status_update/tests/review_approved.json
- handlers/status_update/tests/review_changes.json
> Update PR status on reviews.
