servo/highfive

- handlers/watchers/watchers.ini
It adds more noise than it’s useful.
> Remove myself from watchers

- handlers/homu_status/__init__.py
- handlers/homu_status/tests/json/builders/test_builder_result.json
- handlers/homu_status/tests/json/builders/test_stdio
- handlers/homu_status/tests/tests_failed.json
- newpr.py
- test.py
This makes use of homu's JSON API to get the test output from stdout and comment on the PR in the event of a test failure.
@jdm I didn't make use of the error summary log, because there seem to be some discrepancies between stdout and the log. For instance, the log doesn't have the stacktraces sometimes<sup>[1]</sup>.
We need the stacktraces because:
1) we need the whole log related to the failure (so that we don't have to visit the `stdio` page again
2) we can make highfive more intelligent (in the near future) by posting "retry" messages to @bors-servo referencing the relevant intermittent issues or opening a new issue (which will save more time for us!), and for opening new intermittent-related issues, we'll be needing the stacktrace.
<sup>[1]: See this build's …
> Make highfive post the test failures from homu

- handlers/homu_status/__init__.py
- newpr.py
`get_page_content` seemed to throw an exception when I tried locally. It turned out that `with` actually calls the `__enter__` and `__exit__` methods on a file descriptor. While `file` has those methods, `urlopen` doesn't (which explains why the tests passed locally) - it always throws an `AttributeError`. This should just work if the thing's properly closed.
> urllib2.urlopen should be properly closed to avoid exceptions

- eventhandler.py
The handlers are separate modules but were loaded over each other into a
single module called `__init__`. This resulted in unintended shared
global scope.
This PR is based on #90 which should be merged first.
> Do not load all handlers into module `__init__`.

- handlers/assign_reviewer/__init__.py
- handlers/assign_reviewer/tests/no-reviewer.json
collaborators.ini is a subset of the people with review privileges, so it's not enough to validate potential assignees against it.
> Allow users not present in collaborators.ini to be assigned

- newpr.py
- test.py
Include handler with its associated tests. This way, a test will only target a specific handler instead of executing all handlers
fixes #117
> Include handler with its associated tests

- handlers/watchers/__init__.py
- handlers/watchers/tests/new_pr_author_is_not_watcher.json
- handlers/watchers/tests/new_pr_author_is_watcher.json
- In /handlers/watchers/__init__.py check user:{login:} against watcher for a file/directory
- Added a new test, new_pr_author_is_watcher.json with test_user as the PR author; Assumed that a file/directory will only have 1 watcher, otherwise some tests would fail.
- Modified the existing test to include the :user and :login in the payload; Renamed to new_pr_author_not_a_watcher.json
>  Do not notify watcher when watcher is PR author (fixes issue #128)

- handlers/status_update/__init__.py
- handlers/status_update/tests/synchronize_changes.json
GitHub has started to send emails when commits are pushed.
If there's any other reason for keeping it, happy to close it :)
> status-update: Don't comment when there are pushes

- handlers/homu_status/__init__.py
> unescape HTML entities in test failure output

- eventhandler.py
- handlers/empty_title_element/__init__.py
- handlers/missing_test/__init__.py
- handlers/no_modify_css_tests/__init__.py
- handlers/nonini_wpt_meta/__init__.py
- handlers/unsafe/__init__.py
- handlers/watchers/__init__.py
- helpers.py
- newpr.py
Moves diff header parsing logic out of the handlers and into the `APIProvider` class. This allows the code to be reused, reduces the amount of code to maintain, and simplifies the handlers' logic
Fixes #47
> Consolidate diff parsing logic

- json_cleanup.py
- test.py
#100 revealed a bug in our JSON cleaner. It worked well so far, because almost all the stuff we have in those test JSONs are key/value pairs. We currently detect unused nodes by marking the used ones whenever we do a `__getitem__`. We don't mark them while iterating, because (almost all the time), we're iterating to find the key/value pairs or list items, and so we'll end up marking a lot of nodes which will otherwise be unused.
Currently, we have two problems. Firstly, a payload can have lists (search results, for example), where we can do a great deal of things like list comprehension, mapping, etc. and get the objects. 
Say, we do something like `[issue['number'] for issue in issues]`. Now, `issue['number']` will be marked (because we do a `getitem`), but the individual list items …
> JSON cleaner should properly handle lists

- handlers/missing_test/__init__.py
- handlers/missing_test/tests/test_binding.json
I can't say I really understood how the tests work--hard to tell what's being tested when there's no live repository--, but I went ahead and added one anyway. Fixes #49.
> Don't warn if files with tests for bindings are modified

- handlers/missing_test/__init__.py
- handlers/missing_test/tests/new_pr.json
This addresses issue #167 - Let me know if you'd rather not slam the entire sub-dir path in `TEST_DIRS_TO_CHECK` and instead do something like COMPILE_TEST_DIRS_TO_CHECK
> also check 'compiletest/plugin/compile-fail' test dir on a new PR

- handlers/easy_info/__init__.py
- handlers/easy_info/tests/assign_already_assigned.json
- handlers/easy_info/tests/assign_new.json
- handlers/label_watchers/__init__.py
- handlers/no_modify_css_tests/__init__.py
- handlers/status_update/__init__.py
- handlers/watchers/__init__.py
@jdm What say if we have something like this? (just asking)
> Allow highfive to assign issues on user request

- handlers/label_watchers/watchers.ini
I don't want things like https://github.com/servo/servo/issues/15729 (where someone volunteered and nobody replied for 12 days) to happen again, so I plan to instruct people to file stylo mentored issues under the `A-stylo` label, and I'll watch them to (try to) prevent this.
> Let me watch stylo issues.

- handlers/label_watchers/__init__.py
- handlers/label_watchers/tests/dont_annoy.json
- handlers/label_watchers/tests/dont_label_sender.json
- handlers/label_watchers/tests/new_pr.json
- handlers/label_watchers/tests/not_watched.json
- json_cleanup.py
Highfive currently *annoys* label watchers by cc'ing them multiple times if an issue has the labels they watch (like [this](https://github.com/servo/servo/issues/16171#issuecomment-289876982) for example, and I think I'm the victim most of the time). This PR is a fix for that.
> Don't annoy label watchers

- newpr.py
Instead of checking if token is present in which case Python searches for a global variable named 'token' and errors out.
> Check if self.token is present

- handlers/status_update/__init__.py
- handlers/status_update/labels.ini
- handlers/status_update/tests/custom_labels.json
When events occur on a PR (open, close, merge, etc.),
support adding or removing custom labels through a new config file,
with per-repository settings.
The driving use case for this is to add `S-needs-deploy` to merged
PRs in the saltfs repository to keep track of what's been deployed.
Fixes #179.
> Support custom label actions per repository

- handlers/label_watchers/tests/dont_annoy.json
- handlers/label_watchers/watchers.ini
This test was using the actual servo repo data and tests were failing because of this in #182. Converted these to test data to prevent these kind of failures.
> Use test data in label watcher test

- handlers/watchers/watchers.ini
Tracking minimum rust version bumps.
> Add rillian to watchers.

- handlers/assign_reviewer/__init__.py
This allows PR descriptions to include instructions like "r? mbrubeck" without sending extraneous email when the PR is merged to other repos.
> Make @ optional in "r? username" comments

- handlers/easy_info/__init__.py
This PR updates the message to include a Zulip link and removes the Matrix link.
> Update the easy info message to include zulip link

- handlers/easy_info/__init__.py
Fixes #220. This didn't used to be possible for users who were not members of the organization, but now it is!
> Set assignee upon request.
